name: Makefile CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Check Makefile
          run: make

        - name: Compiles Binary
          run: | 
                make all
                make clean
